package com.autocare.service;

import com.autocare.dto.response.*;import com.autocare.entity.*;import com.autocare.exception.*;import com.autocare.repository.*;import com.autocare.security.*;import jakarta.transaction.Transactional;import org.apache.pdfbox.pdmodel.*;import org.apache.pdfbox.pdmodel.font.*;import org.springframework.security.access.AccessDeniedException;import org.springframework.stereotype.Service;import java.io.*;import java.util.*;

@Service @Transactional
public class HistoryPdfService {
 private final VehicleRepository vehicles;private final ServiceCaseRepository cases;private final ServiceIssueRepository issues;private final ServiceItemRepository items;private final CurrentUserService current;
 public HistoryPdfService(VehicleRepository v,ServiceCaseRepository c,ServiceIssueRepository i,ServiceItemRepository si,CurrentUserService x){vehicles=v;cases=c;issues=i;items=si;current=x;}
 public List<ServiceHistoryResponse> history(String vehicleId){Vehicle v=vehicle(vehicleId);access(v);return cases.findByVehicle_VehicleId(vehicleId).stream().sorted(Comparator.comparing(ServiceCase::getCheckInTime,Comparator.nullsLast(Comparator.reverseOrder()))).map(this::history).toList();}
 public byte[] pdf(String id)throws IOException{ServiceCase c=caseAccess(id);try(PDDocument d=new PDDocument();ByteArrayOutputStream out=new ByteArrayOutputStream()){d.addPage(new PDPage());try(PDPageContentStream s=new PDPageContentStream(d,d.getPage(0))){s.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA),12);s.beginText();s.setLeading(16);s.newLineAtOffset(50,750);for(String line:lines(c)){s.showText(line.length()>100?line.substring(0,100):line);s.newLine();}s.endText();}d.save(out);return out.toByteArray();}}
 private List<String> lines(ServiceCase c){Vehicle v=c.getVehicle();Customer cu=c.getCustomer();List<String>x=new ArrayList<>(List.of("AutoCare Manager - Service Document","Service Case: "+c.getServiceCaseId(),"Customer: "+cu.getName()+" | "+cu.getPhone(),"Vehicle: "+v.getMake()+" "+v.getModel()+" | "+v.getColor()+" | "+v.getLicensePlate(),"Visit: "+c.getVisitType()+" | Service: "+c.getServiceType()+" | Priority: "+c.getPriority(),"Customer Issue: "+value(issue(c)),"Diagnosis: "+value(c.getDiagnosis()),"Work Performed: "+value(c.getSolution()),"Check-in: "+value(c.getCheckInTime()),"Service Items:"));for(ServiceItem i:items.findByServiceCase_ServiceCaseId(c.getServiceCaseId()))x.add("- "+i.getName()+" x"+i.getQuantity());x.add("Customer Signature: ______________________________");x.add("Workshop Representative: _________________________");return x;}
 private ServiceHistoryResponse history(ServiceCase c){return new ServiceHistoryResponse(c.getServiceCaseId(),c.getVisitType(),c.getServiceType(),c.getPriority(),c.getStatus(),issue(c),c.getDiagnosis(),c.getSolution(),items.findByServiceCase_ServiceCaseId(c.getServiceCaseId()).stream().map(i->new ServiceItemResponse(i.getId(),i.getName(),i.getDescription(),i.getQuantity())).toList(),c.getCheckInTime(),c.getReadyForPickupAt());}
 private String issue(ServiceCase c){return issues.findByServiceCase_ServiceCaseId(c.getServiceCaseId()).stream().findFirst().map(ServiceIssue::getIssueDescription).orElse(null);}private String value(Object x){return x==null?"N/A":x.toString();}private Vehicle vehicle(String id){return vehicles.findByVehicleId(id).orElseThrow(()->new ResourceNotFoundException("Vehicle not found"));}private ServiceCase caseAccess(String id){ServiceCase c=cases.findByServiceCaseId(id).orElseThrow(()->new ResourceNotFoundException("Service case not found"));access(c.getVehicle());return c;}private void access(Vehicle v){CurrentUser u=current.requireCurrentUser();if(Set.of("EMPLOYEE","MANAGER","OWNER").contains(u.role()))return;Customer c=current.requireCurrentCustomer();if(!v.getCustomer().getId().equals(c.getId()))throw new AccessDeniedException("You cannot access this vehicle");}
}
