package com.autocare.service;

import com.autocare.dto.request.VehicleRequest; import com.autocare.dto.response.VehicleResponse; import com.autocare.entity.Customer; import com.autocare.entity.Vehicle; import com.autocare.exception.DuplicateResourceException; import com.autocare.exception.ResourceNotFoundException; import com.autocare.repository.VehicleRepository; import com.autocare.security.CurrentUser; import com.autocare.security.CurrentUserService;
import jakarta.persistence.EntityManager; import jakarta.transaction.Transactional; import org.springframework.stereotype.Service; import java.util.List;
@Service @Transactional
public class VehicleService {
 private final VehicleRepository vehicles; private final CustomerService customers; private final CurrentUserService current; private final EntityManager entityManager;
 public VehicleService(VehicleRepository vehicles, CustomerService customers, CurrentUserService current, EntityManager entityManager) { this.vehicles=vehicles; this.customers=customers; this.current=current; this.entityManager=entityManager; }
 public VehicleResponse create(String customerId, VehicleRequest request) { Customer customer=customers.find(customerId); customers.assertCanAccess(customer); String plate=request.licensePlate().trim(); if(vehicles.findByLicensePlateIgnoreCase(plate).isPresent()) throw new DuplicateResourceException("A vehicle with this license plate already exists"); Vehicle vehicle=new Vehicle(nextId(),customer,request.make().trim(),request.model().trim(),request.color().trim(),plate); vehicle.update(request.make().trim(),request.model().trim(),request.year(),request.color().trim(),plate,blankToNull(request.vin()),request.currentMileage()); return toResponse(vehicles.save(vehicle)); }
 public VehicleResponse get(String vehicleId) { Vehicle vehicle=find(vehicleId); customers.assertCanAccess(vehicle.getCustomer()); return toResponse(vehicle); }
 public VehicleResponse update(String vehicleId, VehicleRequest request) { Vehicle vehicle=find(vehicleId); customers.assertCanAccess(vehicle.getCustomer()); String plate=request.licensePlate().trim(); vehicles.findByLicensePlateIgnoreCase(plate).filter(other -> !other.getId().equals(vehicle.getId())).ifPresent(other -> { throw new DuplicateResourceException("A vehicle with this license plate already exists"); }); vehicle.update(request.make().trim(),request.model().trim(),request.year(),request.color().trim(),plate,blankToNull(request.vin()),request.currentMileage()); return toResponse(vehicle); }
 public List<VehicleResponse> search(String search) { CurrentUser actor=current.requireCurrentUser(); customers.requireWorkshop(actor); List<Vehicle> result=(search==null||search.isBlank())?vehicles.findAll():vehicles.findByLicensePlateContainingIgnoreCaseOrMakeContainingIgnoreCaseOrModelContainingIgnoreCase(search.trim(),search.trim(),search.trim()); return result.stream().map(this::toResponse).toList(); }
 private Vehicle find(String id) { return vehicles.findByVehicleId(id).orElseThrow(() -> new ResourceNotFoundException("Vehicle not found")); }
 private String nextId() { Number next=(Number)entityManager.createNativeQuery("select nextval('vehicle_business_id_seq')").getSingleResult(); return "VEH-%06d".formatted(next.longValue()); }
 private String blankToNull(String value) { return value==null||value.isBlank()?null:value.trim(); }
 private VehicleResponse toResponse(Vehicle v) { return new VehicleResponse(v.getVehicleId(),v.getCustomer().getCustomerId(),v.getMake(),v.getModel(),v.getYear(),v.getColor(),v.getLicensePlate(),v.getVin(),v.getCurrentMileage(),v.getCreatedAt(),v.getUpdatedAt()); }
}
