package com.autocare.controller;

import com.autocare.entity.Customer; import com.autocare.entity.User; import com.autocare.enums.AuthenticationType; import com.autocare.enums.UserRole; import com.autocare.repository.CustomerRepository; import com.autocare.repository.UserRepository; import com.autocare.security.JwtService;
import org.junit.jupiter.api.Test; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.test.context.ActiveProfiles; import org.springframework.test.web.servlet.MockMvc; import org.springframework.transaction.annotation.Transactional;
import static org.springframework.http.MediaType.APPLICATION_JSON; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@SpringBootTest @AutoConfigureMockMvc @ActiveProfiles("test") @Transactional
class CustomerVehicleIntegrationTest {
 @Autowired MockMvc mvc; @Autowired UserRepository users; @Autowired CustomerRepository customers; @Autowired JwtService jwt; @Autowired PasswordEncoder encoder;
 @Test void workshopCanCreateSearchAndUpdateCustomerWithVehicles() throws Exception { String token=token(UserRole.EMPLOYEE,"phase4-employee"); String customer=mvc.perform(post("/api/v1/customers").header("Authorization",token).contentType(APPLICATION_JSON).content("{\"name\":\"Jane Smith\",\"phone\":\"555-1111\",\"email\":\"jane@example.test\"}")).andExpect(status().isCreated()).andExpect(jsonPath("$.customerId").value(org.hamcrest.Matchers.startsWith("CUS-"))).andReturn().getResponse().getContentAsString().replaceAll(".*\\\"customerId\\\":\\\"([^\\\"]+)\\\".*","$1"); mvc.perform(post("/api/v1/customers/"+customer+"/vehicles").header("Authorization",token).contentType(APPLICATION_JSON).content("{\"make\":\"Toyota\",\"model\":\"Camry\",\"color\":\"Blue\",\"licensePlate\":\"P4-TEST-1\"}")).andExpect(status().isCreated()).andExpect(jsonPath("$.vehicleId").value(org.hamcrest.Matchers.startsWith("VEH-"))); mvc.perform(get("/api/v1/customers").header("Authorization",token).param("search","Jane")).andExpect(status().isOk()).andExpect(jsonPath("$[0].name").value("Jane Smith")); mvc.perform(put("/api/v1/customers/"+customer).header("Authorization",token).contentType(APPLICATION_JSON).content("{\"name\":\"Jane Doe\",\"phone\":\"555-2222\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.name").value("Jane Doe")); }
 @Test void customerCanOnlyAccessOwnCustomerAndVehicleRecords() throws Exception { User first=user("phase4-customer-a",UserRole.CUSTOMER); Customer own=new Customer("CUS-OWN-A","Own Customer","555-1"); own.assignUser(first); customers.save(own); User other=user("phase4-customer-b",UserRole.CUSTOMER); Customer privateCustomer=new Customer("CUS-OWN-B","Other Customer","555-2"); privateCustomer.assignUser(other); customers.save(privateCustomer); String ownToken=bearer(first); mvc.perform(get("/api/v1/customers/CUS-OWN-A").header("Authorization",ownToken)).andExpect(status().isOk()); mvc.perform(get("/api/v1/customers/CUS-OWN-B").header("Authorization",ownToken)).andExpect(status().isForbidden()); mvc.perform(post("/api/v1/customers/CUS-OWN-B/vehicles").header("Authorization",ownToken).contentType(APPLICATION_JSON).content("{\"make\":\"Honda\",\"model\":\"Civic\",\"color\":\"White\",\"licensePlate\":\"P4-NO\"}")).andExpect(status().isForbidden()); }
 @Test void duplicateLicensePlateAndUnauthenticatedAccessAreRejected() throws Exception { String token=token(UserRole.EMPLOYEE,"phase4-employee-2"); String customer=mvc.perform(post("/api/v1/customers").header("Authorization",token).contentType(APPLICATION_JSON).content("{\"name\":\"Plate Owner\",\"phone\":\"555-9\"}")).andReturn().getResponse().getContentAsString().replaceAll(".*\\\"customerId\\\":\\\"([^\\\"]+)\\\".*","$1"); String payload="{\"make\":\"Ford\",\"model\":\"Focus\",\"color\":\"Red\",\"licensePlate\":\"P4-DUP\"}"; mvc.perform(post("/api/v1/customers/"+customer+"/vehicles").header("Authorization",token).contentType(APPLICATION_JSON).content(payload)).andExpect(status().isCreated()); mvc.perform(post("/api/v1/customers/"+customer+"/vehicles").header("Authorization",token).contentType(APPLICATION_JSON).content(payload)).andExpect(status().isConflict()); mvc.perform(get("/api/v1/customers")).andExpect(status().isUnauthorized()); }
 private User user(String username,UserRole role){return users.save(new User(username,encoder.encode("TestPassword123!"),username+"@test.local",role,AuthenticationType.LOCAL));} private String token(UserRole role,String username){return bearer(user(username,role));} private String bearer(User user){return "Bearer "+jwt.createToken(user.getId(),user.getUsername(),user.getRole().name(),user.getAuthenticationType().name());}
}
