package com.autocare.enums;
public enum ServiceCaseStatus { APPOINTMENT, CHECKED_IN, DIAGNOSIS, WAITING_FOR_APPROVAL, IN_SERVICE, PAYMENT_PENDING, READY_FOR_PICKUP, DELIVERED, COMPLETED, CANCELLED, ON_HOLD }
